# Generated by Django 5.0.4 on 2024-05-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=120, null=True)),
                ('date_of_birth', models.DateField(default='2000-01-01')),
                ('gender', models.CharField(max_length=10, null=True)),
                ('PhoneNumber', models.CharField(max_length=20, null=True)),
                ('EmailAddress', models.EmailField(max_length=254, null=True, unique=True)),
                ('Password', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
