# Generated by Django 5.0.4 on 2024-05-03 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cardnumber', models.PositiveIntegerField()),
                ('HolderName', models.CharField(max_length=120)),
                ('ExpirationDate', models.DateField()),
                ('cvv', models.PositiveIntegerField()),
                ('Card_Type', models.CharField(max_length=120)),
                ('athlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.athlet')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('Type', models.CharField(max_length=120)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('athlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.athlet')),
            ],
        ),
    ]
