# Generated by Django 5.0.4 on 2024-05-03 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameExercice', models.CharField(max_length=120)),
                ('Description', models.CharField(max_length=120)),
                ('Url', models.URLField()),
                ('difficulty_level', models.CharField(default='INTERMEDIATE', max_length=120)),
                ('MostActiveMuscle', models.CharField(max_length=120)),
                ('Equipments', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Repitition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveSmallIntegerField()),
                ('rep', models.PositiveSmallIntegerField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveIntegerField(null=True)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workouts.exercice')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subscriptions.subscription')),
            ],
        ),
    ]
