# Generated by Django 5.0.4 on 2024-05-03 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.PositiveIntegerField()),
                ('bmi', models.FloatField()),
                ('fitness_level', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('athlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.athlet')),
            ],
        ),
    ]
